/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <rcc.h>

int main(void) {
    //RCC_CFGR    = 0x00080002;   // 0000 0000 0000 1000 0000 0000 0000 0010;
    //RCC_CR      = 0x01000000;   // 0000 0001 0000 0000 0000 0000 0000 0000;
    // PLL
    
    /* Loop forever */
	for(;;);
}
